---
- name: Cloning GIT repository & Deploy webapp
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Cloning Git repository
      git:
        repo: https://github.com/RayRayGH/CLASE_3_Python.git
        dest: /home/ubuntu/ansible-git-webapp/webapp
        update: yes
        force: yes

    - name: Install Python dependencies
      pip:
        requirements: /home/ubuntu/ansible-git-webapp/requirements.txt

    - name: Install Gunicorn and Nginx
      apt:
        name:
          - nginx
          - gunicorn3
        state: present

    - name: Configure Nginx
      copy:
        src: /home/ubuntu/ansible-git-webapp/nginx.conf
        dest: /etc/nginx/sites-available/webapp
      notify: reload nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/webapp
        dest: /etc/nginx/sites-enabled/webapp
        state: link

    - name: Configure Gunicorn service
      template:
        src: /home/ubuntu/ansible-git-webapp/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
      notify: restart gunicorn

    - name: Start Gunicorn service
      systemd:
        name: gunicorn
        state: started
        enabled: yes

  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

    - name: restart gunicorn
      systemd:
        name: gunicorn
        state: restarted